### ISSUE TITLE
Vomit distance inconsistency

### ISSUE THREAD

**Issue by lunatixxx** [lunatixxx/RCVMod#68]
Sometimes it seems that the boomer can puke a little further than what it should be able to (compared to vanilla) definitely caused by the higher tickrate. Maybe it can be tweaked with z_vomit_velocity but it might be difficult to find the good value and even there it could still be inconsistent so it will not be a priority considering it barely affect the gameplay, it is more a reminder for not forget about it for now. Closing issue and will reopen later.

**Comment by A1mDev** [comment]
z_vomit_velocity has no effect on the range and speed of the vomit, otherwise the patch in the tickrate activator would not be needed. This variable only affects particles, nothing else. Particles are what you see when vomiting occurs.

**Comment by lunatixxx** [comment]
https://forums.alliedmods.net/showpost.php?p=2722796&postcount=168

From default tickrate to 128 on CSGO, the set up for the smokes are not the same (more velocity). Pretty much the same engine (or close) so i will not be surprised it has similar problems.
